apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
    - name: web
      image: 524714122815.dkr.ecr.us-east-1.amazonaws.com/app:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ecr-registry